// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:d86832be-6204-42f5-97fb-d010ff2a5c2b',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_nM9jYih4T',
  aws_user_pools_web_client_id: '5u615amec60bj6hilmb9qodlk5',
  oauth: {},
};

export default awsconfig;
